# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

# Other Spring Boot properties
